//! Raw FFI bindings for libibverbs (RDMA Verbs).
//!
//! Generated by `pegaflow-transfer/build.rs` when the `v2` feature is on.
#![allow(warnings)]

include!(concat!(env!("OUT_DIR"), "/libibverbs-bindings.rs"));
