use std::collections::{HashMap, hash_map::Entry};
use std::sync::Arc;

use log::error;
use parking_lot::Mutex;
use uuid::Uuid;

use crate::block::{BlockKey, SealedBlock};
use crate::cache::{CacheInsertOutcome, TinyLfuCache};
use crate::metrics::core_metrics;

pub(super) struct ReadCache {
    inner: Mutex<ReadCacheInner>,
}

struct ReadCacheInner {
    cache: TinyLfuCache<BlockKey, Arc<SealedBlock>>,
    /// Key: UUID generated by ReserveLoad.
    load_leases: HashMap<String, LoadLease>,
    /// Aggregated refcounts by block key for attribution metrics.
    /// Value: (footprint_bytes, total_refcount)
    leased_for_load_by_key: HashMap<BlockKey, (u64, usize)>,
}

struct LoadLease {
    instance_id: String,
    blocks: Vec<(BlockKey, Arc<SealedBlock>)>,
    remaining_refs: usize,
}

impl ReadCacheInner {
    fn decrement_lease_ref_for_key(&mut self, block_key: &BlockKey) {
        if let Some((bytes, total)) = self.leased_for_load_by_key.get_mut(block_key) {
            *total = total.saturating_sub(1);
            if *total == 0 {
                let bytes_val = *bytes;
                self.leased_for_load_by_key.remove(block_key);
                core_metrics()
                    .leased_for_load_unique_bytes
                    .add(-(bytes_val as i64), &[]);
            }
        } else {
            error!(
                "BUG: leased_for_load_by_key missing key: namespace={} hash_len={}",
                block_key.namespace,
                block_key.hash.len()
            );
        }
    }

    fn decrement_lease_refs_for_key(&mut self, block_key: &BlockKey, refs: usize) {
        for _ in 0..refs {
            self.decrement_lease_ref_for_key(block_key);
        }
    }
}

impl ReadCache {
    pub(super) fn new(
        capacity_bytes: usize,
        enable_lfu_admission: bool,
        value_size_hint: Option<usize>,
    ) -> Self {
        let cache =
            TinyLfuCache::new_unbounded(capacity_bytes, enable_lfu_admission, value_size_hint);
        Self {
            inner: Mutex::new(ReadCacheInner {
                cache,
                load_leases: HashMap::new(),
                leased_for_load_by_key: HashMap::new(),
            }),
        }
    }

    pub(super) fn contains_keys(&self, keys: &[BlockKey]) -> Vec<bool> {
        let inner = self.inner.lock();
        keys.iter().map(|k| inner.cache.contains_key(k)).collect()
    }

    /// Scan cache for a prefix of `keys`, stopping at the first miss.
    pub(super) fn get_prefix_blocks(
        &self,
        keys: &[BlockKey],
    ) -> (usize, Vec<(BlockKey, Arc<SealedBlock>)>) {
        let mut hit = 0usize;
        let mut blocks = Vec::new();
        {
            let mut inner = self.inner.lock();
            for key in keys {
                if let Some(block) = inner.cache.get(key) {
                    hit += 1;
                    blocks.push((key.clone(), Arc::clone(&block)));
                } else {
                    break;
                }
            }
        }
        (hit, blocks)
    }

    pub(super) fn batch_insert(&self, blocks: Vec<(BlockKey, Arc<SealedBlock>)>) {
        let mut inner = self.inner.lock();
        for (key, block) in blocks {
            let footprint_bytes = block.memory_footprint();
            match inner.cache.insert(key, block) {
                CacheInsertOutcome::InsertedNew => {
                    let m = core_metrics();
                    m.cache_block_insertions.add(1, &[]);
                    m.cache_resident_bytes.add(footprint_bytes as i64, &[]);
                }
                CacheInsertOutcome::AlreadyExists => {}
                CacheInsertOutcome::Rejected => {
                    core_metrics().cache_block_admission_rejections.add(1, &[]);
                }
            }
        }
    }

    /// Create a load lease for `num_workers` consumers that will each consume it once.
    pub(super) fn create_load_lease(
        &self,
        instance_id: &str,
        num_workers: usize,
        blocks: &[(BlockKey, Arc<SealedBlock>)],
    ) -> Option<String> {
        if blocks.is_empty() {
            return None;
        }

        let lease_id = Uuid::new_v4().to_string();
        let mut inner = self.inner.lock();
        for (key, block) in blocks {
            let footprint = block.memory_footprint();

            match inner.leased_for_load_by_key.entry(key.clone()) {
                Entry::Occupied(mut o) => {
                    o.get_mut().1 += num_workers;
                }
                Entry::Vacant(v) => {
                    v.insert((footprint, num_workers));
                    core_metrics()
                        .leased_for_load_unique_bytes
                        .add(footprint as i64, &[]);
                }
            }
        }

        inner.load_leases.insert(
            lease_id.clone(),
            LoadLease {
                instance_id: instance_id.to_string(),
                blocks: blocks.to_vec(),
                remaining_refs: num_workers,
            },
        );
        Some(lease_id)
    }

    /// Consume a load lease once, returning owned [`Arc<SealedBlock>`] handles.
    #[cfg_attr(
        feature = "tracing",
        fastrace::trace(name = "storage.consume_load_lease")
    )]
    pub(super) fn consume_load_lease(
        &self,
        instance_id: &str,
        load_lease_id: &str,
    ) -> Result<Vec<Arc<SealedBlock>>, String> {
        let mut inner = self.inner.lock();
        let Some(lease) = inner.load_leases.get(load_lease_id) else {
            return Err(format!("missing load lease {load_lease_id}"));
        };
        if lease.instance_id != instance_id {
            return Err(format!(
                "load lease {load_lease_id} belongs to instance {}, not {instance_id}",
                lease.instance_id
            ));
        }

        let result: Vec<Arc<SealedBlock>> = lease
            .blocks
            .iter()
            .map(|(_, block)| Arc::clone(block))
            .collect();
        let keys: Vec<BlockKey> = lease.blocks.iter().map(|(key, _)| key.clone()).collect();
        let remove_lease = lease.remaining_refs <= 1;

        if remove_lease {
            inner.load_leases.remove(load_lease_id);
        } else if let Some(lease) = inner.load_leases.get_mut(load_lease_id) {
            lease.remaining_refs -= 1;
        }

        for key in &keys {
            inner.decrement_lease_ref_for_key(key);
        }

        Ok(result)
    }

    pub(super) fn load_lease_len(
        &self,
        instance_id: &str,
        load_lease_id: &str,
    ) -> Result<usize, String> {
        let inner = self.inner.lock();
        let Some(lease) = inner.load_leases.get(load_lease_id) else {
            return Err(format!("missing load lease {load_lease_id}"));
        };
        if lease.instance_id != instance_id {
            return Err(format!(
                "load lease {load_lease_id} belongs to instance {}, not {instance_id}",
                lease.instance_id
            ));
        }

        Ok(lease.blocks.len())
    }

    /// Release an entire load lease. Idempotent for cancellation paths.
    pub(super) fn release_load_lease(&self, load_lease_id: &str) -> bool {
        let mut inner = self.inner.lock();
        let Some(lease) = inner.load_leases.remove(load_lease_id) else {
            return false;
        };

        for (key, _) in &lease.blocks {
            inner.decrement_lease_refs_for_key(key, lease.remaining_refs);
        }

        true
    }

    /// Look up specific blocks by key without prefix-scan semantics (does not
    /// stop at first miss). Used by the serving side of cross-node transfer.
    pub(super) fn get_blocks(&self, keys: &[BlockKey]) -> Vec<(BlockKey, Arc<SealedBlock>)> {
        let mut inner = self.inner.lock();
        let mut found = Vec::new();
        for key in keys {
            if let Some(block) = inner.cache.get(key) {
                found.push((key.clone(), Arc::clone(&block)));
            }
        }
        found
    }

    pub(super) fn remove_lru_batch(&self, batch_size: usize) -> Vec<(BlockKey, Arc<SealedBlock>)> {
        let mut inner = self.inner.lock();
        (0..batch_size)
            .map_while(|_| inner.cache.remove_lru())
            .collect()
    }

    pub(super) fn remove_all(&self) -> Vec<(BlockKey, Arc<SealedBlock>)> {
        self.inner.lock().cache.remove_all()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_cache() -> ReadCache {
        ReadCache::new(1 << 20, false, None)
    }

    fn make_block() -> Arc<SealedBlock> {
        Arc::new(SealedBlock::from_slots(Vec::new()))
    }

    #[test]
    fn get_blocks_returns_existing_skips_missing() {
        let cache = make_cache();
        let key1 = BlockKey::new("ns".into(), vec![1]);
        let key2 = BlockKey::new("ns".into(), vec![2]);
        let key3 = BlockKey::new("ns".into(), vec![3]);

        cache.batch_insert(vec![
            (key1.clone(), make_block()),
            (key3.clone(), make_block()),
        ]);

        // key2 is missing — get_blocks should skip it (unlike prefix scan, no break)
        let result = cache.get_blocks(&[key1.clone(), key2.clone(), key3.clone()]);
        assert_eq!(result.len(), 2);
        assert_eq!(result[0].0, key1);
        assert_eq!(result[1].0, key3);
    }

    #[test]
    fn get_blocks_empty_input_returns_empty() {
        let cache = make_cache();
        let result = cache.get_blocks(&[]);
        assert!(result.is_empty());
    }

    #[test]
    fn get_blocks_all_missing_returns_empty() {
        let cache = make_cache();
        let key1 = BlockKey::new("ns".into(), vec![10]);
        let key2 = BlockKey::new("ns".into(), vec![20]);

        let result = cache.get_blocks(&[key1, key2]);
        assert!(result.is_empty());
    }

    #[test]
    fn get_blocks_is_idempotent() {
        let cache = make_cache();
        let key = BlockKey::new("ns".into(), vec![1]);
        cache.batch_insert(vec![(key.clone(), make_block())]);

        // Call get_blocks twice; both should return the same result
        let result1 = cache.get_blocks(std::slice::from_ref(&key));
        let result2 = cache.get_blocks(std::slice::from_ref(&key));
        assert_eq!(result1.len(), 1);
        assert_eq!(result2.len(), 1);
        assert_eq!(result1[0].0, result2[0].0);

        assert!(!cache.release_load_lease("missing-lease"));
    }

    #[test]
    fn get_blocks_does_not_break_at_first_miss() {
        // Contrast with get_prefix_blocks which stops at first miss
        let cache = make_cache();
        let keys: Vec<BlockKey> = (0u8..5)
            .map(|i| BlockKey::new("ns".into(), vec![i]))
            .collect();

        // Insert only even-indexed keys: 0, 2, 4
        for key in keys.iter().step_by(2) {
            cache.batch_insert(vec![(key.clone(), make_block())]);
        }

        // get_blocks: returns keys 0, 2, 4 (skips 1, 3)
        let result = cache.get_blocks(&keys);
        assert_eq!(result.len(), 3);

        // get_prefix_blocks: stops at key 1 (first miss), returns only key 0
        let (prefix_hit, _) = cache.get_prefix_blocks(&keys);
        assert_eq!(prefix_hit, 1);
    }

    #[test]
    fn remove_all_evicts_resident_blocks() {
        let cache = make_cache();
        let key1 = BlockKey::new("ns".into(), vec![1]);
        let key2 = BlockKey::new("ns".into(), vec![2]);

        cache.batch_insert(vec![
            (key1.clone(), make_block()),
            (key2.clone(), make_block()),
        ]);

        let removed = cache.remove_all();
        assert_eq!(removed.len(), 2);
        assert_eq!(cache.get_blocks(&[key1, key2]).len(), 0);
        assert!(cache.remove_all().is_empty());
    }
}
